### PR TITLE
Graceful shutdown

### PR DESCRIPTION
**Pull request by kuzeyron**
Added graceful shutdown in case it bothers other people.

### CODE REVIEW

**Comment by kuzeyron** [comment]
It's when I exit the app it's giving me those threading messages which doesn't have to be there. Might frightened some people. I did some testings before I added this PR.
`Setting daemon=True` usually fixes everything that have to exit the app and hiding messages.

**Comment by kuzeyron** [comment]
It's when I exit the app it's giving me those threading messages which doesn't have to be there. Might frightened some people. I did some testings before I added this PR.
Setting `daemon=True` usually fixes everything that have to exit the app and hiding messages from threading. I think it's documented somewhere about being good for just that.

**Comment by kuzeyron** [comment]
Here you go:
```
[INFO   ] [Logger      ] Record log in /home/user/.kivy/logs/kivy_19-08-29_17.txt
[INFO   ] [Kivy        ] v1.11.0
[INFO   ] [Kivy        ] Installed at "/usr/lib/python3.7/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.7.4 (default, Jul 16 2019, 07:12:58) 
[GCC 9.1.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python3"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [ImageLoaderFFPy] Using ffpyplayer 4.3.0.dev0
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_ffpyplayer, img_gif 
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 19.1.4'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) Haswell Mobile '>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event11
[INFO   ] [MTD         ] Read event from </dev/input/event11>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [MTD         ] </dev/input/event11> range position X is 1232 - 5710
[INFO   ] [MTD         ] </dev/input/event11> range position Y is 1156 - 4696
[INFO   ] [MTD         ] </dev/input/event11> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event11> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event11> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event11> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event11> rotation set to 0
[INFO   ] [WindowSDL   ] exiting mainloop and closing.
[INFO   ] [Base        ] Leaving application in progress...
[CRITICAL] [ffpyplayer  ] __call__() takes 1 positional argument but 3 were given
[CRITICAL] [ffpyplayer  ] Traceback (most recent call last):
  File "ffpyplayer/player/core.pyx", line 95, in ffpyplayer.player.core.read_thread_enter
  File "ffpyplayer/player/core.pyx", line 2231, in ffpyplayer.player.core.VideoState.read_thread
  File "ffpyplayer/player/core.pyx", line 2250, in ffpyplayer.player.core.VideoState.failed
  File "ffpyplayer/player/core.pyx", line 384, in ffpyplayer.player.core.VideoState.request_thread_s
  File "ffpyplayer/player/core.pyx", line 399, in ffpyplayer.player.core.VideoState.request_thread_py
TypeError: __call__() takes 1 positional argument but 3 were given
[CRITICAL] [ffpyplayer  ] __call__() takes 1 positional argument but 3 were given
[CRITICAL] [ffpyplayer  ] Traceback (most recent call last):
  File "ffpyplayer/player/core.pyx", line 135, in ffpyplayer.player.core.audio_thread_enter
  File "ffpyplayer/player/core.pyx", line 1047, in ffpyplayer.player.core.VideoState.audio_thread
  File "ffpyplayer/player/core.pyx", line 384, in ffpyplayer.player.core.VideoState.request_thread_s
  File "ffpyplayer/player/core.pyx", line 399, in ffpyplayer.player.core.VideoState.request_thread_py
TypeError: __call__() takes 1 positional argument but 3 were given
[CRITICAL] [ffpyplayer  ] __call__() takes 1 positional argument but 3 were given
[CRITICAL] [ffpyplayer  ] Traceback (most recent call last):
  File "ffpyplayer/player/core.pyx", line 115, in ffpyplayer.player.core.video_thread_enter
  File "ffpyplayer/player/core.pyx", line 1255, in ffpyplayer.player.core.VideoState.video_thread
  File "ffpyplayer/player/core.pyx", line 384, in ffpyplayer.player.core.VideoState.request_thread_s
  File "ffpyplayer/player/core.pyx", line 399, in ffpyplayer.player.core.VideoState.request_thread_py
TypeError: __call__() takes 1 positional argument but 3 were given
```

**Comment by matham** [comment]
So yeah, that means there's an actual bug there that needs to be fixes. 

Setting the thread as daemon would make the error go away by simply terminating the thread before it can hit the error, but at the cost of the player not cleaning up after itself which isn't good. So this PR is not an appropriate solution to the underlying bug.

Thanks for the effort though.

**Comment by matham** [comment]
If you like you can open a bug report, but I'm not sure I'll get to it soon.

**Comment by kuzeyron** [comment]
Then this is a bug report!

**Comment by matham** [comment]
I meant in the issues section, rather then as a PR.

**Comment by kuzeyron** [comment]
You know the issue so take your time!

**Pull request closed without merging**
